import 'package:flutter/material.dart';
import 'package:solar_icons/solar_icons.dart';

class AppIcons {
  static const IconData login = SolarIconsOutline.login_2;
  static const IconData profile = SolarIconsOutline.userRounded;
  static const IconData globe = SolarIconsOutline.global;
  static const IconData heart = SolarIconsOutline.heart;
  static const IconData heartBold = SolarIconsBold.heart;
  static const IconData car = SolarIconsOutline.wheel;
  static const IconData carBold = SolarIconsBold.wheel;
  static const IconData search = SolarIconsOutline.magnifier;
  static const IconData filter = SolarIconsOutline.filters;
  static const IconData calendar = SolarIconsOutline.calendar;
  static const IconData closeCircle = SolarIconsOutline.closeCircle;
  static const IconData home = SolarIconsOutline.home;
  static const IconData homeBold = SolarIconsBold.home;
  static const IconData logout = SolarIconsOutline.logout;
  static const IconData add = SolarIconsOutline.addCircle;
  static const IconData office = SolarIconsOutline.buildings;
  static const IconData officeBold = SolarIconsBold.buildings;
  static const IconData verified = SolarIconsBold.shieldCheck;
  static const IconData shield = SolarIconsOutline.shieldCheck;
  static const IconData dashboard = SolarIconsOutline.widget_4;
  static const IconData document = SolarIconsOutline.documentText;
  static const IconData phone = SolarIconsOutline.phone;
  static const IconData delete = SolarIconsOutline.trashBinTrash;
  static const IconData edit = SolarIconsOutline.pen;
  static const IconData star = SolarIconsBold.star;
  static const IconData location = SolarIconsOutline.mapPoint;
  static const IconData whatsapp = SolarIconsOutline.chatRoundDots;
  static const IconData call = SolarIconsOutline.phoneCallingRounded;
  static const IconData share = SolarIconsOutline.share;
  static const IconData visibility = SolarIconsOutline.eye;
  static const IconData visibilityOff = SolarIconsOutline.eyeClosed;
  static const IconData email = SolarIconsOutline.letter;
  static const IconData lock = SolarIconsOutline.lockKeyholeMinimalistic;
  static const IconData person = SolarIconsOutline.user;
  static const IconData store = SolarIconsOutline.garage;
  static const IconData checkCircle = SolarIconsBold.checkCircle;
  static const IconData arrowBack = SolarIconsOutline.altArrowLeft;
  static const IconData arrowForward = SolarIconsOutline.altArrowRight;
  static const IconData moreVert = SolarIconsOutline.menuDots;
  static const IconData image = SolarIconsOutline.gallery;
  static const IconData cameraAlt = SolarIconsOutline.camera;
  static const IconData info = SolarIconsOutline.infoCircle;
  static const IconData settings = SolarIconsOutline.settings;
  static const IconData fuel = SolarIconsOutline.fuel;
  static const IconData transmission = SolarIconsOutline.transmission;
  static const IconData seats = SolarIconsOutline.usersGroupRounded;
  static const IconData sort = SolarIconsOutline.sort;
  static const IconData user = SolarIconsOutline.user;
  static const IconData notification = SolarIconsOutline.bell;
  static const IconData chevronDown = SolarIconsOutline.altArrowDown;
  static const IconData chevronLeft = SolarIconsOutline.altArrowLeft;
}
